package com.example.repository

import com.example.data.Question

enum class Difficulty {
    EASY, MEDIUM, HARD
}

class QuestionRepository {

    private val easyQuestions = listOf(
        Question("Happy", "Feeling or showing pleasure or contentment", "Feeling angry and resentful", "Being bored or tired", "Experiencing cold or hunger"),
        Question("Gigantic", "Extremely large in size or scale", "Very small and fragile", "Fast moving and elusive", "Dull and uninteresting"),
        Question("Brief", "Of short duration; concise and quick", "Extremely long and boring", "Very expensive and high quality", "Unstable and shaky"),
        Question("Ancient", "Belonging to the very distant past", "Brand new and modern", "Very hot and humid", "Extremely quiet and peaceful"),
        Question("Broad", "Having a wide distance from side to side", "Very narrow and thin", "Highly intelligent and creative", "Sorrowful and grieving"),
        Question("Silent", "Completely quiet; making no sound", "Extremely loud and rowdy", "Bright and shining brightly", "Heavy and hard to carry"),
        Question("Brave", "Ready to face and endure danger or pain", "Filled with fear and anxiety", "Selfish and unkind", "Lazy and unproductive"),
        Question("Calm", "Free from agitation, excitement, or storm", "Extremely angry and violent", "Very crowded and noisy", "Completely frozen"),
        Question("Tiny", "Extremely small in size", "Enormously large", "Heavy and dense", "Loud and boisterous"),
        Question("Quick", "Moving or capable of moving at high speed", "Very slow and sluggish", "Dull and uninspiring", "Polite and respectful"),
        Question("Clever", "Quick to understand, learn, and devise ideas", "Stubborn and refuse to learn", "Extremely rude and hostile", "Weak and easily broken"),
        Question("Cruel", "Willfully causing pain or suffering to others", "Kind and compassionate", "Generous and giving", "Shy and quiet"),
        Question("Damp", "Slightly wet or moist", "Extremely bone dry", "Very hot and boiling", "Frozen solid"),
        Question("Dull", "Lacking interest, excitement, or brightness", "Highly exciting and vibrant", "Sharp and focused", "Polite and charming"),
        Question("Fancy", "Elaborate, decorative, or sophisticated", "Plain and extremely simple", "Very cheap and affordable", "Broken and unusable"),
        Question("Fierce", "Having or displaying an intense aggressiveness", "Gentle and harmless", "Weak and submissive", "Silent and peaceful"),
        Question("Gentle", "Mild, kind, or tender in temperament", "Aggressive, rough, and violent", "Loud and noisy", "Very fast and rapid"),
        Question("Hollow", "Having an empty space inside", "Solid all the way through", "Extremely heavy", "Bright and shining"),
        Question("Humble", "Having or showing a modest estimate of one's importance", "Arrogant, proud, and boastful", "Highly wealthy", "Extremely lazy"),
        Question("Lazy", "Unwilling to work or use energy", "Active, energetic, and productive", "Very smart and intelligent", "Generous and kind"),
        Question("Loyal", "Giving or showing firm support or allegiance", "Deceitful and treacherous", "Silly and comical", "Weak and fragile"),
        Question("Mild", "Gentle and not severe, sharp, or strong", "Extremely harsh or intense", "Bitterly cold", "Very loud and chaotic"),
        Question("Narrow", "Of small width in proportion to length", "Broad and wide", "Highly elevated", "Deep and hollow"),
        Question("Odd", "Different from what is usual or expected; strange", "Common and ordinary", "Beautiful and elegant", "Extremely simple"),
        Question("Polite", "Having or showing behavior that is respectful and considerate", "Rude, insolent, and disrespectful", "Shy and reserved", "Wealthy and powerful"),
        Question("Proud", "Feeling deep pleasure or satisfaction as a result of achievements", "Ashamed and humiliated", "Humble and modest", "Anxious and worried"),
        Question("Rude", "Offensively impolite or ill-mannered", "Polite, kind, and respectful", "Quick and prompt", "Wise and knowledgeable"),
        Question("Sharp", "Having an edge or point that is able to cut or pierce", "Dull, blunt, and rounded", "Soft and pliable", "Smooth and flat"),
        Question("Shy", "Being nervous or timid in the company of other people", "Outgoing, confident, and bold", "Proud and arrogant", "Fast and energetic"),
        Question("Simple", "Easily understood or done; presenting no difficulty", "Complex, intricate, and difficult", "Elegant and fancy", "Very expensive"),
        Question("Sincere", "Free from pretense or deceit; genuine", "Dishonest, hypocritical, or fake", "Proud and loud", "Quiet and reserved"),
        Question("Smooth", "Having an even and regular surface; free from projections", "Rough, bumpy, or coarse", "Wet and slippery", "Sharp and pointy"),
        Question("Steep", "Rising or falling sharply; nearly perpendicular", "Flat, level, or gradual", "Short and narrow", "Deep and hollow"),
        Question("Stiff", "Not easily bent or changed in shape; rigid", "Flexible, pliable, and soft", "Hot and boiling", "Liquid and running"),
        Question("Swift", "Moving or capable of moving with great speed", "Slow, sluggish, and delayed", "Heavy and bulky", "Stiff and rigid"),
        Question("Tender", "Showing gentleness, kindness, or affection", "Harsh, unfeeling, and severe", "Tough and hard", "Quick and sudden"),
        Question("Tense", "Stretched tight; anxious, nervous, or unable to relax", "Relaxed, calm, and peaceful", "Happy and content", "Bored and listless"),
        Question("Tough", "Strong and resilient; able to endure hardship", "Weak, fragile, and soft", "Gentle and kind", "Dry and smooth"),
        Question("Vast", "Of very great extent or quantity; immense", "Tiny, small, and limited", "Short and brief", "Dense and crowded"),
        Question("Weak", "Lacking physical strength or energy", "Strong, robust, and powerful", "Smart and clever", "Loud and boisterous"),
        Question("Wealthy", "Having a great deal of money, resources, or assets", "Poor, destitute, and broke", "Lazy and unproductive", "Humble and modest"),
        Question("Wild", "Living or growing in the natural state; untamed", "Tame, domesticated, or calm", "Quiet and peaceful", "Fancy and luxurious"),
        Question("Wise", "Having or showing experience, knowledge, and good judgment", "Foolish, ignorant, or silly", "Young and immature", "Quick and rapid"),
        Question("Bold", "Showing an ability to take risks; confident and courageous", "Timid, fearful, and shy", "Generous and polite", "Simple and plain"),
        Question("Cozy", "Giving a feeling of comfort, warmth, and relaxation", "Cold, uncomfortable, or hostile", "Spacious and vast", "Loud and chaotic"),
        Question("Dawn", "The first appearance of light in the sky before sunrise", "Dusk, or sunset in the evening", "Midnight with total darkness", "Midday with bright sun"),
        Question("Dusk", "The darker stage of twilight in the evening", "Dawn or early morning sunrise", "Noon with high sun", "Midnight with no light"),
        Question("Echo", "A sound cause by the reflection of sound waves", "Absolute silence", "A bright flash of light", "A sweet fragrance"),
        Question("Fade", "Gradually grow faint and disappear", "Appear suddenly out of nowhere", "Grow larger and brighter", "Make a loud noise"),
        Question("Flee", "Run away from a place or situation of danger", "Stand firm and fight", "Arrive and greet others", "Sleep peacefully"),
        Question("Gaze", "Look steadily and intently, especially in admiration or thought", "Glance briefly and look away", "Close eyes completely", "Listen very carefully"),
        Question("Glare", "Stare in an angry or fierce way", "Smile warmly and kindly", "Sleep deeply", "Whisper quietly"),
        Question("Hint", "A slight or indirect indication or clue", "Direct statement or full explanation", "Loud shout of warning", "Physical obstacle"),
        Question("Leap", "Jump or spring a long way, to a great height, or with great force", "Crawl slowly along the ground", "Sit down quietly", "Stand perfectly still"),
        Question("Lend", "Grant to someone the use of something on the understanding that it will be returned", "Borrow or take from someone", "Steal or destroy", "Sell for high profit"),
        Question("Melt", "Make or become liquefied by heating", "Freeze or turn into a solid", "Evaporate and vanish", "Break into pieces"),
        Question("Pace", "A single step taken when walking or running", "A complete rest or standstill", "A loud scream", "A heavy object"),
        Question("Peak", "The pointed top of a mountain", "The flat base of a valley", "A deep ocean trench", "A wide open plain"),
        Question("Rise", "Move from a lower position to a higher one", "Fall, sink, or go down", "Stay in a fixed place", "Spin around rapidly"),
        Question("Seek", "Attempt to find or desire to obtain", "Avoid or run away from", "Throw away or discard", "Forget completely"),
        Question("Slam", "Shut a door or lid forcefully and with a loud noise", "Open extremely gently", "Lock securely with a key", "Paint a bright color"),
        Question("Bitter", "Having a sharp, pungent, unpleasant taste or smell", "Sweet, sugary, and delicious", "Mild, tasteless, and bland", "Fragrant and floral"),
        Question("Blend", "Mix different substances or ingredients together", "Separate or divide into parts", "Freeze solid", "Heat to boiling point"),
        Question("Bound", "Walk or run with leaping strides", "Stand completely still", "Sit down on a chair", "Crawl extremely slowly"),
        Question("Charm", "The power or quality of giving delight or arousing admiration", "Ugliness or offensive quality", "A physical threat or weapon", "A feeling of deep sorrow"),
        Question("Cling", "Hold on tightly to someone or something", "Let go or release instantly", "Throw far away", "Run around in circles"),
        Question("Craft", "An activity involving skill in making things by hand", "Mass automated destruction", "Sleeping or daydreaming", "A sudden natural disaster"),
        Question("Creep", "Move slowly and carefully, especially in order to avoid being noticed", "Run or dash at full speed", "Fly high in the sky", "Scream loudly"),
        Question("Dread", "Anticipate with great apprehension or fear", "Look forward to with extreme joy", "Forget entirely about the future", "Laugh uncontrollably"),
        Question("Float", "Rest or move slowly on the surface of a liquid without sinking", "Sink immediately to the bottom", "Fly at supersonic speeds", "Melt into liquid")
    )

    private val mediumQuestions = listOf(
        Question("Abandon", "Cease to support or look after; desert", "Keep, maintain, or preserve", "Repair or rebuild", "Adopt and protect"),
        Question("Accurate", "Correct in all details; exact", "Inaccurate, wrong, or flawed", "Vague and approximate", "Deceitful and lying"),
        Question("Advocate", "Publicly recommend or support a cause", "Oppose or speak out against", "Ignore and ignore entirely", "Doubt or question"),
        Question("Aggressive", "Ready or likely to attack or confront", "Peaceful, friendly, and mild", "Shy and introverted", "Generous and giving"),
        Question("Ambition", "A strong desire to do or to achieve something", "Apathy or lack of interest", "A deep, peaceful sleep", "Feeling of regret"),
        Question("Analyze", "Examine methodically and in detail for explanation", "Ignore or neglect completely", "Synthesize or put together", "Praise highly"),
        Question("Appreciate", "Recognize the full worth of; be grateful for", "Undervalue, despise, or ignore", "Request additional payment", "Change or modify"),
        Question("Artificial", "Made or produced by human beings rather than occurring naturally", "Natural, genuine, or real", "Highly expensive and premium", "Weak and poorly made"),
        Question("Associate", "Connect someone or something in one's mind", "Separate or dissociate", "Forget or lose track of", "Argue or fight with"),
        Question("Ban", "Officially or legally prohibit", "Allow, permit, or approve", "Create a new law", "Ignore the regulations"),
        Question("Barrier", "A circumstance or obstacle that keeps people or things apart", "An open pathway or connection", "A useful support tool", "A decorative ornament"),
        Question("Benefit", "An advantage or profit gained from something", "A disadvantage, loss, or harm", "A small physical chore", "An administrative rule"),
        Question("Candidate", "A person who applies for a job or is nominated for election", "An employer or interviewer", "A bystander or spectator", "A retired official"),
        Question("Category", "A class or division of people or things regarded as having shared characteristics", "A state of total chaos", "An individual item", "A unique exception"),
        Question("Cease", "Bring or come to an end", "Start, begin, or continue", "Increase in magnitude", "Modify or adjust slightly"),
        Question("Chaos", "Complete disorder and confusion", "Perfect order and harmony", "A solid physical structure", "A tiny minor mistake"),
        Question("Collapse", "Fall down or in; give way", "Build up, stand, or strengthen", "Expand and grow larger", "Float high in the air"),
        Question("Combine", "Join or merge to form a single unit", "Separate, divide, or isolate", "Destroy or break down", "Rotate rapidly"),
        Question("Complex", "Consisting of many different and connected parts", "Simple, plain, and straightforward", "Cheap and low quality", "Unstable and shaky"),
        Question("Confirm", "Establish the truth or correctness of", "Deny, refute, or contradict", "Ignore or leave undecided", "Ask a question about"),
        Question("Contrast", "Compare in order to show unlikeness or vast differences", "Align in complete agreement", "Ignore completely", "Combine together"),
        Question("Debate", "A formal discussion on a particular topic in a public meeting", "An undisputed fact or agreement", "A continuous friendly silence", "A physical competition"),
        Question("Decline", "Become smaller, fewer, or less; decrease", "Increase, grow, or improve", "Stay completely constant", "Accept eagerly"),
        Question("Demonstrate", "Clearly show the existence or truth of something by giving proof", "Hide, conceal, or cover up", "Ignore or neglect", "Doubt or question"),
        Question("Device", "A thing made or adapted for a particular purpose, especially mechanical/electronic", "A natural wilderness area", "A simple abstract thought", "An old historical book"),
        Question("Disastrous", "Causing great damage or severe hardship", "Highly beneficial and successful", "Moderately inconvenient", "Boring and unexciting"),
        Question("Diversity", "The state of showing a great deal of variety; variety", "Sameness, uniformity, or monotony", "Great physical strength", "Deep concentration"),
        Question("Dominate", "Have a commanding influence on; exercise control over", "Submit to, obey, or serve", "Ignore or withdraw from", "Cooperate on equal terms"),
        Question("Drastic", "Likely to have a strong or far-reaching effect; extreme", "Mild, moderate, or gentle", "Slow and gradual", "Completely ineffective"),
        Question("Efficient", "Achieving maximum productivity with minimum wasted effort", "Wasteful, slow, or incompetent", "Expensive and high-end", "Extremely quick but chaotic"),
        Question("Emphasize", "Give special importance or prominence to something", "Downplay, ignore, or minimize", "Explain briefly in passing", "Doubt or criticize"),
        Question("Encounter", "Unexpectedly experience or be faced with", "Avoid, escape, or bypass", "Plan in advance carefully", "Forget thoroughly"),
        Question("Enhance", "Intensify, increase, or further improve the quality or value", "Worsen, diminish, or degrade", "Maintain unchanged", "Create from scratch"),
        Question("Equivalent", "Equal in value, amount, function, or meaning", "Different, unequal, or opposite", "Highly superior or better", "Cheap and low grade"),
        Question("Evolve", "Develop gradually, especially from a simple to a more complex form", "Stay static or regress", "Decline suddenly", "Disappear completely"),
        Question("Exclude", "Deny someone or something access to or bar from a place/group", "Include, admit, or welcome", "Study deeply", "Coordinate together"),
        Question("Expand", "Become larger or more extensive; grow", "Shrink, contract, or narrow", "Remain fixed in size", "Divide into pieces"),
        Question("Flexible", "Capable of bending easily without breaking; adaptable", "Rigid, stiff, and stubborn", "Weak and fragile", "Expensive and luxurious"),
        Question("Fundamental", "Forming a necessary base or core; of central importance", "Secondary, trivial, or minor", "Complex and advanced", "Highly unusual or rare"),
        Question("Guarantee", "Provide a formal assurance or promise, especially for performance/quality", "Repudiate, deny, or refuse", "Request feedback from", "Sell at a high price"),
        Question("Hostile", "Unfriendly; antagonistic or opposed", "Friendly, warm, and amiable", "Quiet and reserved", "Indifferent and neutral"),
        Question("Illusion", "A deceptive appearance or impression; false belief", "Reality, truth, or fact", "A long-held dream", "A sharp physical image"),
        Question("Impact", "The action of one object coming forcibly into contact with another; effect", "Lack of effect or vacancy", "A gentle, soft breeze", "A quiet whisper"),
        Question("Inevitable", "Certain to happen; unavoidable", "Avoidable, uncertain, or unlikely", "Completely impossible", "Highly desirable"),
        Question("Infinite", "Limitless or endless in space, extent, or size", "Finite, limited, or restricted", "Massive but countable", "Extremely tiny"),
        Question("Innocent", "Not guilty of a crime or offense; simple and naive", "Guilty, culpable, or corrupt", "Smart and calculating", "Dangerous and lethal"),
        Question("Invest", "Put money or effort into financial schemes, shares, or property for profit", "Squander, waste, or spend", "Save in a secure box", "Demand immediate payment"),
        Question("Irony", "The expression of meaning using language that signifies the opposite for humor", "Direct literal speech", "A boring lecture", "A sad tragedy"),
        Question("Justify", "Show or prove to be right or reasonable", "Refute, condemn, or disprove", "Ignore or overlook", "Doubt or question"),
        Question("Legitimate", "Conforming to the law or to rules; valid", "Illegal, invalid, or fake", "Very expensive", "Unusually smart"),
        Question("Logical", "According to the rules of logic or formal argument; reasonable", "Irrational, illogical, or absurd", "Unusually creative", "Extremely simple"),
        Question("Maintain", "Cause or enable a state or condition to continue", "Neglect, abandon, or stop", "Change or modify", "Destroy or rupture"),
        Question("Manipulate", "Handle or control in a skillful, often unfair or devious manner", "Leave alone or treat honestly", "Build carefully by hand", "Destroy forcefully"),
        Question("Minimize", "Reduce to the smallest possible amount or degree", "Maximize, expand, or inflate", "Ignore or overlook", "Observe carefully"),
        Question("Neutral", "Not helping or supporting either side in a conflict; impartial", "Biased, partisan, or active", "Completely disconnected", "Highly aggressive"),
        Question("Obstacle", "A thing that blocks one's way or prevents progress", "An aid, asset, or pathway", "A goals or objective", "A simple reward"),
        Question("Opponent", "Someone who competes against or fights another in a contest/game", "Ally, partner, or teammate", "Spectator or fan", "Referee or judge"),
        Question("Persist", "Continue firmly or obstinately in an opinion or course of action", "Give up, quit, or yield", "Change direction frequently", "Sleep or rest"),
        Question("Potential", "Having or showing the capacity to become or develop into something in future", "Actual, realized, or current", "Impossible or incapable", "Useless and broken"),
        Question("Precise", "Marked by accuracy and detail; exact", "Vague, imprecise, or general", "Rough and chaotic", "Lying and deceitful"),
        Question("Predict", "Say or estimate that a specified event will happen in the future", "Review or recall the past", "Observe the present", "Express total doubt"),
        Question("Proficient", "Competent or skilled in doing or using something", "Incompetent, unskilled, or amateur", "Highly eager but weak", "Slow and sluggish"),
        Question("Rational", "Based on or in accordance with reason or logic", "Irrational, emotional, or crazy", "Highly creative", "Unusual or strange"),
        Question("Reject", "Dismiss as inadequate, unacceptable, or faulty", "Accept, approve, or adopt", "Modify and submit again", "Ignore entirely"),
        Question("Resilient", "Able to withstand or recover quickly from difficult conditions", "Fragile, weak, or easily broken", "Rigid and unyielding", "Stubborn and angry"),
        Question("Reveal", "Make previously unknown or secret information known to others", "Hide, conceal, or cover", "Create a new lie", "Forget completely"),
        Question("Significant", "Sufficiently great or important to be worthy of attention", "Insignificant, trivial, or minor", "Highly unusual", "Very expensive"),
        Question("Subtle", "So delicate or precise as to be difficult to analyze or describe", "Obvious, blunt, or distinct", "Extremely loud and bright", "Weak and fragile"),
        Question("Sustain", "Strengthen or support physically or mentally over time", "Weaken, deplete, or interrupt", "Create or invent", "Observe or inspect"),
        Question("Acquire", "Buy or obtain an asset or object for oneself", "Lose, forfeit, or give away", "Search for thoroughly", "Destroy or break down")
    )

    private val hardQuestions = listOf(
        Question("Aberration", "A departure from what is normal, usual, or expected", "A standard or typical example", "A physical achievement", "A state of total agreement"),
        Question("Alacrity", "Brisk and cheerful readiness to act", "Reluctance, apathy, or sluggishness", "Intense anger or hostility", "Deep sorrow or grief"),
        Question("Anachronism", "A thing belonging to a period other than that in which it exists", "A perfect chronological order", "A device used for navigation", "A secret conspiracy"),
        Question("Antipathy", "A deep-seated feeling of dislike; aversion", "Strong liking, affinity, or love", "Total indifference", "A clever strategy"),
        Question("Articulate", "Having or showing the ability to speak fluently and coherently", "Inarticulate, tongue-tied, or silent", "Deceitful and lying", "Extremely loud"),
        Question("Ascetic", "Characterized by severe self-discipline and abstention from all luxury", "Sybaritic, self-indulgent, or luxurious", "Highly social and outgoing", "Extremely intellectual"),
        Question("Audacious", "Showing a willingness to take surprisingly bold risks", "Timid, cowardly, or cautious", "Calm and peaceful", "Rude and disrespectful"),
        Question("Cacophony", "A harsh, discordant mixture of sounds", "Euphony, harmony, or sweet music", "A beautiful painting", "Absolute quiet silence"),
        Question("Capricious", "Given to sudden and unaccountable changes of mood or behavior", "Consistent, stable, and predictable", "Highly stubborn and rigid", "Extremely quiet"),
        Question("Castigate", "Reprimand or punish someone severely", "Praise, laud, or compliment", "Pardon or release fully", "Instruct gently"),
        Question("Cogent", "Clear, logical, and highly convincing", "Incoherent, weak, or unconvincing", "Extremely loud and long", "Deceptive and fake"),
        Question("Conundrum", "A confusing and difficult problem or question", "A simple and obvious solution", "A clear direct statement", "A long historical epic"),
        Question("Corroborate", "Confirm or give support to a statement, theory, or finding", "Contradict, refute, or deny", "Ignore or overlook", "Question or investigate"),
        Question("Deference", "Humble submission and respect", "Disrespect, insolence, or contempt", "Fear and anxiety", "Joyful celebration"),
        Question("Decorum", "Behavior in keeping with good taste and propriety", "Impropriety, rudeness, or bad taste", "A state of total confusion", "An intense argument"),
        Question("Demagogue", "A political leader who seeks support by appealing to popular desires/prejudices", "A wise, rational statesman", "A quiet silent observer", "A military general"),
        Question("Deride", "Express contempt for; ridicule or mock", "Praise, respect, or admire", "Pity or show sympathy", "Ignore completely"),
        Question("Desiccate", "Remove the moisture from something; dry out thoroughly", "Moisten, hydrate, or wet", "Freeze solid", "Melt completely"),
        Question("Diatribe", "A forceful and bitter verbal attack against someone or something", "Eulogy, praise, or commendation", "A quiet whisper", "A friendly conversation"),
        Question("Didactic", "Intended to teach, particularly in having moral instruction as an ulterior motive", "Uninstructive or non-educational", "Highly amusing and funny", "Confusing and chaotic"),
        Question("Dilatory", "Slow to act; intended to cause delay", "Prompt, fast, and efficient", "Extremely active", "Stiff and rigid"),
        Question("Disparate", "Essentially different in kind; not allowing comparison", "Identical, similar, or uniform", "Highly connected and joined", "Vast and immense"),
        Question("Dissemble", "Conceal one's true motives, feelings, or beliefs", "Reveal, express honestly, or show", "Investigate others thoroughly", "Argue loudly"),
        Question("Dissonance", "A lack of harmony or agreement among components", "Consonance, harmony, or agreement", "A continuous solid structure", "A tiny minor mistake"),
        Question("Ebullient", "Cheerful and full of energy", "Depressed, somber, or listless", "Angry and aggressive", "Shy and reserved"),
        Question("Eclectic", "Deriving ideas, style, or taste from a broad and diverse range of sources", "Narrow, uniform, or monolithic", "Highly expensive", "Extremely old-fashioned"),
        Question("Enervate", "Cause someone to feel drained of energy or vitality; weaken", "Energize, invigorate, or strengthen", "Calm down or soothe", "Confront aggressively"),
        Question("Ephemeral", "Lasting for a very short time; transient", "Permanent, eternal, or long-lasting", "Unusually expensive", "Strong and resilient"),
        Question("Equivocal", "Open to more than one interpretation; ambiguous", "Unambiguous, clear, and direct", "False and lying", "Sly and clever"),
        Question("Erudite", "Having or showing great knowledge or learning", "Ignorant, uneducated, or foolish", "Shy and conservative", "Highly wealthy"),
        Question("Esoteric", "Intended for or likely to be understood by only a small number of specialists", "Commonly known, public, or popular", "Highly boring and tedious", "Beautiful and elegant"),
        Question("Eulogy", "A speech or piece of writing that praises someone highly, typically deceased", "Vilification, diatribe, or condemnation", "A formal debate", "A physical threat"),
        Question("Exculpate", "Show or declare that someone is not guilty of wrongdoing", "Convict, accuse, or blame", "Fine or penalize financially", "Forgive superficially"),
        Question("Exigent", "Pressing; demanding; requiring immediate attention", "Trivial, easy, or non-urgent", "Very boring and slow", "Stiff and stubborn"),
        Question("Fawn", "Display exaggerated flattery or affection, typically to gain favor", "Rebel, oppose, or show contempt", "Run away in fear", "Sleep peacefully"),
        Question("Garrulous", "Excessively talkative, especially on trivial matters", "Taciturn, reticent, or silent", "Very smart and educational", "Incompetent"),
        Question("Gregarious", "Fond of company; sociable", "Introverted, unsociable, or hostile", "Highly emotional", "Fragile and weak"),
        Question("Harangue", "A lengthy and aggressive speech; lecture forcefully", "A brief, friendly conversation", "A quiet silent whisper", "A formal code of law"),
        Question("Iconoclast", "A person who attacks cherished beliefs or established institutions", "Conformist or traditionalist", "A skilled artist", "A religious leader"),
        Question("Impetuous", "Acting or done quickly and without thought or care", "Cautious, deliberate, and thoughtful", "Extremely slow", "Polite and respectful"),
        Question("Inchoate", "Just begun and so not fully formed or developed; rudimentary", "Fully developed, mature, or finished", "Completely broken", "Extremely old"),
        Question("Inimical", "Tending to obstruct or harm; unfriendly; hostile", "Amiable, friendly, or beneficial", "Quiet and indifferent", "Extremely fast"),
        Question("Innocuous", "Not harmful or offensive; safe", "Harmful, toxic, or offensive", "Highly expensive", "Intelligent and clever"),
        Question("Intrepid", "Fearless; adventurous; courageous", "Cowardly, timid, or fearful", "Proud and arrogant", "Generous and kind"),
        Question("Laconic", "Using very few words; concise to the point of seeming rude", "Verbose, wordy, or talkative", "Highly polite", "Extremely loud"),
        Question("Loquacious", "Tending to talk a great deal; talkative", "Reticent, silent, or taciturn", "Smart and intellectual", "Sad and depressing"),
        Question("Lucid", "Expressed clearly; easy to understand; rational", "Vague, confusing, or obscure", "Excited and energetic", "Dark and gloomy"),
        Question("Maverick", "An unorthodox or independent-minded person", "Conformist, follower, or traditionalist", "A skilled politician", "An inactive spectator"),
        Question("Mitigate", "Make less severe, serious, or painful", "Aggravate, worsen, or intensify", "Build or construct", "Ignore completely"),
        Question("Obdurate", "Stubbornly refusing to change one's opinion or course of action", "Compliant, flexible, or yielding", "Anxious and worried", "Kind and gentle"),
        Question("Obsequious", "Obedient or attentive to an excessive or servile degree", "Domineering, assertive, or independent", "Quiet and reserved", "Highly rude"),
        Question("Opaque", "Not able to be seen through; not transparent; hard to understand", "Transparent, clear, or easy", "Solid but light", "Soft and crumbly"),
        Question("Ostentatious", "Characterized by vulgar or pretentious display; designed to impress", "Modest, quiet, or simple", "Cheap and low quality", "Ugly and repellent"),
        Question("Pedantic", "Excessively concerned with minor details or rules; academic", "Careless, general, or casual", "Highly creative", "Useless and idle"),
        Question("Perfidy", "Deceitfulness; untrustworthiness; betrayal of trust", "Fidelity, loyalty, or trustworthiness", "A smart trick", "A heavy physical force"),
        Question("Pragmatic", "Dealing with things sensibly and realistically in a practical way", "Idealistic, impractical, or unrealistic", "Highly emotional and volatile", "Extremely rare"),
        Question("Precipitate", "Cause to happen suddenly, unexpectedly, or prematurely", "Delay, slow down, or prevent", "Choose carefully", "Observe quietly"),
        Question("Prodigal", "Spending money or resources freely and recklessly; wastefully extravagant", "Frugal, thrifty, or parsimonious", "Generous and charitable", "Extremely poor"),
        Question("Propriety", "The state or quality of conforming to conventionally accepted standards of behavior", "Impropriety, rudeness, or misbehavior", "Deep intellectual thought", "Complete chaos"),
        Question("Quiescent", "In a state or period of temporary inactivity or dormancy", "Active, vibrant, or restless", "Completely dead", "Extremely fast"),
        Question("Recondite", "Little known; abstruse; obscure", "Well-known, simple, or popular", "Highly boring and dry", "Extremely short"),
        Question("Reticent", "Not revealing one's thoughts or feelings readily", "Talkative, loquacious, or expressive", "Polite and respectful", "Proud and boastful"),
        Question("Soporific", "Tending to induce drowsiness or sleep", "Stimulating, energizing, or keeping awake", "Extremely interesting", "Calm and quiet"),
        Question("Specious", "Superficially plausible, but actually wrong", "Genuine, valid, and correct", "Highly attractive", "Dull and boring"),
        Question("Tacit", "Understood or implied without being directly stated", "Explicit, spoken, or written", "Completely secret", "Understood by no one"),
        Question("Taciturn", "Reserved or uncommunicative in speech; saying little", "Talkative, garrulous, or verbose", "Loud and angry", "Silly and comical"),
        Question("Terse", "Sparing in the use of words; abrupt and concise", "Prolix, verbose, or wordy", "Gentle and polite", "Confusing and vague"),
        Question("Venerate", "Regard with great respect; revere", "Despise, condemn, or disrespect", "Pity or show mercy", "Ignore completely"),
        Question("Vociferous", "Vehement or clamorous; crying out noisily", "Quiet, silent, or soft-spoken", "Highly intelligent", "Extremely rapid"),
        Question("Avarice", "Extreme greed for wealth or material gain", "Generosity, charity, or selflessness", "Great intelligence", "Intense anger")
    )

    fun getQuestions(difficulty: Difficulty): List<Question> {
        return when (difficulty) {
            Difficulty.EASY -> easyQuestions
            Difficulty.MEDIUM -> mediumQuestions
            Difficulty.HARD -> hardQuestions
        }
    }
}
